chore(action): update github action #16

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -65,38 +65,39 @@ jobs:
             npx @wuchuheng/nextjs my-app
           '
       - name: Check the dependencies is installed or not, if not, exit code 127.
-        run: |
-          docker exec ${CONTAINER_NAME} bash -c '
-            export NVM_DIR="$HOME/.nvm"; 
-            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-            cd my-app
-            ls -ahl
-            
-            # Check the dependencies is installed or not,
-            if [ ! -d node_modules ]; then
-              echo "Error: The dependencies is not installed."
-              exit 127
-            fi
-          '
+      #   run: |
+      #     docker exec ${CONTAINER_NAME} bash -c '
+      #       export NVM_DIR="$HOME/.nvm";
+      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+      #       ls -ahl
+      #       cd my-app
+      #       ls -ahl
 
-      - name: Check the programm can be executed or not. if not, exit code 127.
-        run: |
-          docker exec ${CONTAINER_NAME} bash -c '
-            export NVM_DIR="$HOME/.nvm"; 
-            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-            cd my-app
-            
-            # Start the program in the background and capture its PID
-            pnpm run dev & APP_PID=$!
+      #       # Check the dependencies is installed or not,
+      #       if [ ! -d node_modules ]; then
+      #         echo "Error: The dependencies is not installed."
+      #         exit 127
+      #       fi
+      #     '
 
-            # Wait for 10 seconds
-            sleep 10
+      # - name: Check the programm can be executed or not. if not, exit code 127.
+      #   run: |
+      #     docker exec ${CONTAINER_NAME} bash -c '
+      #       export NVM_DIR="$HOME/.nvm";
+      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+      #       cd my-app
 
-            # Check if the process is still running
-            if ps -p $APP_PID > /dev/null; then
-              kill -9 $APP_PID
-            else
-              echo "Error: The program has already exited unexpectedly."
-              exit 127
-            fi
-          '
+      #       # Start the program in the background and capture its PID
+      #       pnpm run dev & APP_PID=$!
+
+      #       # Wait for 10 seconds
+      #       sleep 10
+
+      #       # Check if the process is still running
+      #       if ps -p $APP_PID > /dev/null; then
+      #         kill -9 $APP_PID
+      #       else
+      #         echo "Error: The program has already exited unexpectedly."
+      #         exit 127
+      #       fi
+      #     '
